//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM-Beziehungsmetadaten

[assembly: EdmRelationshipAttribute("ChatProjektModel", "FK__tblVerbin__Benut__0AD2A005", "tblBenutzer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ChatServer.Benutzer), "tblVerbindungen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ChatServer.Verbindung), true)]

#endregion

namespace ChatServer
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class ChatEntities : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues ChatEntities-Objekt mithilfe der in Abschnitt 'ChatEntities' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public ChatEntities() : base("name=ChatEntities", "ChatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues ChatEntities-Objekt.
        /// </summary>
        public ChatEntities(string connectionString) : base(connectionString, "ChatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues ChatEntities-Objekt.
        /// </summary>
        public ChatEntities(EntityConnection connection) : base(connection, "ChatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Benutzer> Benutzer
        {
            get
            {
                if ((_Benutzer == null))
                {
                    _Benutzer = base.CreateObjectSet<Benutzer>("Benutzer");
                }
                return _Benutzer;
            }
        }
        private ObjectSet<Benutzer> _Benutzer;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Verbindung> Verbindungen
        {
            get
            {
                if ((_Verbindungen == null))
                {
                    _Verbindungen = base.CreateObjectSet<Verbindung>("Verbindungen");
                }
                return _Verbindungen;
            }
        }
        private ObjectSet<Verbindung> _Verbindungen;

        #endregion
        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Benutzer'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToBenutzer(Benutzer benutzer)
        {
            base.AddObject("Benutzer", benutzer);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Verbindungen'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToVerbindungen(Verbindung verbindung)
        {
            base.AddObject("Verbindungen", verbindung);
        }

        #endregion
    }
    

    #endregion
    
    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChatProjektModel", Name="Benutzer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Benutzer : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Benutzer-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        public static Benutzer CreateBenutzer(global::System.Int32 id)
        {
            Benutzer benutzer = new Benutzer();
            benutzer.ID = id;
            return benutzer;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ChatProjektModel", "FK__tblVerbin__Benut__0AD2A005", "tblVerbindungen")]
        public EntityCollection<Verbindung> Verbindungen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Verbindung>("ChatProjektModel.FK__tblVerbin__Benut__0AD2A005", "tblVerbindungen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Verbindung>("ChatProjektModel.FK__tblVerbin__Benut__0AD2A005", "tblVerbindungen", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChatProjektModel", Name="Verbindung")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Verbindung : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Verbindung-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="datum">Anfangswert der Eigenschaft Datum.</param>
        public static Verbindung CreateVerbindung(global::System.Int32 id, global::System.DateTime datum)
        {
            Verbindung verbindung = new Verbindung();
            verbindung.ID = id;
            verbindung.Datum = datum;
            return verbindung;
        }

        #endregion
        #region Primitive Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Datum
        {
            get
            {
                return _Datum;
            }
            set
            {
                OnDatumChanging(value);
                ReportPropertyChanging("Datum");
                _Datum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Datum");
                OnDatumChanged();
            }
        }
        private global::System.DateTime _Datum;
        partial void OnDatumChanging(global::System.DateTime value);
        partial void OnDatumChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BenutzerID
        {
            get
            {
                return _BenutzerID;
            }
            set
            {
                OnBenutzerIDChanging(value);
                ReportPropertyChanging("BenutzerID");
                _BenutzerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BenutzerID");
                OnBenutzerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BenutzerID;
        partial void OnBenutzerIDChanging(Nullable<global::System.Int32> value);
        partial void OnBenutzerIDChanged();

        #endregion
    
        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ChatProjektModel", "FK__tblVerbin__Benut__0AD2A005", "tblBenutzer")]
        public Benutzer Benutzer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Benutzer>("ChatProjektModel.FK__tblVerbin__Benut__0AD2A005", "tblBenutzer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Benutzer>("ChatProjektModel.FK__tblVerbin__Benut__0AD2A005", "tblBenutzer").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Benutzer> BenutzerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Benutzer>("ChatProjektModel.FK__tblVerbin__Benut__0AD2A005", "tblBenutzer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Benutzer>("ChatProjektModel.FK__tblVerbin__Benut__0AD2A005", "tblBenutzer", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
